name: drizzle
description: A simple package to persist and query small dataset of data
version: 0.1.0+1
repository: https://github.com/erickzanardo/drizzle

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ">=9.0.0 <11.0.0"

dependencies:
  path: ^1.8.3
  uuid: ^4.3.3
